

spring.application.name=photovault

spring.datasource.url=jdbc:mysql://localhost:3306/sp_learning?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=TIGER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


server.port=8082
file.upload-dir=D:/company_project_Photos_uploads/users
